package org.openxdata.modules.workflows.model.shared;
// Generated Aug 8, 2010 5:31:25 PM by Hibernate Tools 3.2.1.GA

import org.openxdata.server.admin.model.AbstractEditable;
import org.openxdata.server.admin.model.StudyDef;

/**
 * DBSpecStudyMap generated by hbm2java
 */
public class DBSpecStudyMap extends AbstractEditable implements java.io.Serializable {

    private Integer id = 0;
    private DBSpecification specifications;
    private StudyDef study;
    private String xml;

    public DBSpecStudyMap() {
    }

    public DBSpecStudyMap(DBSpecification specifications, StudyDef study) {
        this.specifications = specifications;
        this.study = study;
    }

    public DBSpecStudyMap(DBSpecification specifications, StudyDef study, String xml) {
        this.specifications = specifications;
        this.study = study;
        this.xml = xml;
    }

    @Override
    public int getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public DBSpecification getSpecifications() {
        return this.specifications;
    }

    public void setSpecifications(DBSpecification specifications) {
        this.specifications = specifications;
    }

    public StudyDef getStudy() {
        return this.study;
    }

    public void setStudy(StudyDef study) {
        this.study = study;
    }

    public String getXml() {
        return this.xml;
    }

    public void setXml(String xml) {
        this.xml = xml;
    }
}
