package org.openxdata.modules.workflows.model.shared;
// Generated Aug 8, 2010 5:31:25 PM by Hibernate Tools 3.2.1.GA

import org.openxdata.server.admin.model.AbstractEditable;




/**
 * DBWorkitem generated by hbm2java
 */
public class DBWorkitem extends AbstractEditable implements java.io.Serializable {


     private Integer id = 0;
     private String workitemId;
     private String xml;
     private String state;

    public DBWorkitem() {
    }

    public DBWorkitem(String workitemId, String xml, String state) {
       this.workitemId = workitemId;
       this.xml = xml;
       this.state = state;
    }
   
    @Override
    public int getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getWorkitemId() {
        return this.workitemId;
    }
    
    public void setWorkitemId(String workitemId) {
        this.workitemId = workitemId;
    }
    public String getXml() {
        return this.xml;
    }
    
    public void setXml(String xml) {
        this.xml = xml;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
}


