
(function(){var g=null,k=false;function l(a){this.t={};this.tick=function(b,c,d){d=d?d:(new Date).getTime();this.t[b]=[d,c]};this.tick("start",g,a)}var m=new l;window.GA_jstiming={Timer:l,load:m};if(window.GA_jstiming){window.GA_jstiming.d={};window.GA_jstiming.i=1;var n=function(a,b,c){var d=a.t[b],e=a.t.start;if(d&&(e||c)){d=a.t[b][0];e=c!=undefined?c:e[0];return d-e}};window.GA_jstiming.report=function(a,b,c){var d="";if(a.g)d+="&"+a.g;var e=a.t,f=e.start,h=[],p=[],i;for(i in e)if(i!="start")if(i.indexOf("_")!=0){var q=e[i][1];if(q)e[q]&&p.push(i+"."+n(a,i,e[q][0]));else f&&h.push(i+"."+n(a,i))}delete e.start;if(b)for(var u in b)d+="&"+u+"="+b[u];a=[c?c:"http://csi.gstatic.com/csi","?v=3",
"&s="+(window.GA_jstiming.sn||"gam")+"&action=",a.name,p.length?"&it="+p.join(","):"","",d,"&rt=",h.join(",")].join("");b=new Image;var j=window.GA_jstiming.i++;window.GA_jstiming.d[j]=b;b.onload=b.onerror=function(){delete window.GA_jstiming.d[j]};b.src=a;b=g;return a}};var o=this,r=function(a,b){var c,d=b,e=a.split(".");c=c||o;!(e[0]in c)&&c.execScript&&c.execScript("var "+e[0]);for(var f;e.length&&(f=e.shift());)if(!e.length&&d!==undefined)c[f]=d;else c=c[f]?c[f]:c[f]={}},t=function(a,b){function c(){}c.prototype=b.prototype;a.k=b.prototype;a.prototype=new c};var v=function(){var a="false",b=k;if(a=="true")return true;if(a=="false")return k;return b},w=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,x=function(a,b){if(!a)return b;var c=a.match(w);return c?c[0]:b};var y,z="0.7",A=0,B=parseFloat(z),aa=y=isNaN(B)||B>1||B<0?A:B;var ba=v();var C=function(){return x("","pubads.g.doubleclick.net")};var D=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var E,F,G,H,I=function(){return o.navigator?o.navigator.userAgent:g};H=G=F=E=k;var J;if(J=I()){var ca=o.navigator;E=J.indexOf("Opera")==0;F=!E&&J.indexOf("MSIE")!=-1;G=!E&&J.indexOf("WebKit")!=-1;H=!E&&!G&&ca.product=="Gecko"}var da=E,K=F,L=H,ea=G,M;
a:{var N="",O;if(da&&o.opera){var P=o.opera.version;N=typeof P=="function"?P():P}else{if(L)O=/rv\:([^\);]+)(\)|;)/;else if(K)O=/MSIE\s+([^\);]+)(\)|;)/;else if(ea)O=/WebKit\/(\S+)/;if(O){var Q=O.exec(I());N=Q?Q[1]:""}}if(K){var R,S=o.document;R=S?S.documentMode:undefined;if(R>parseFloat(N)){M=String(R);break a}}M=N}
var fa=M,T={},U=function(a){var b;if(!(b=T[a])){b=T;var c=a,d=a,e=0;a=String(fa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");d=String(d).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");for(var f=Math.max(a.length,d.length),h=0;e==0&&h<f;h++){var p=a[h]||"",i=d[h]||"",q=RegExp("(\\d*)(\\D*)","g"),u=RegExp("(\\d*)(\\D*)","g");do{var j=q.exec(p)||["","",""],s=u.exec(i)||["","",""];if(j[0].length==0&&s[0].length==0)break;e=j[1].length==0?0:parseInt(j[1],10);var ga=s[1].length==0?0:parseInt(s[1],10);
e=D(e,ga)||D(j[2].length==0,s[2].length==0)||D(j[2],s[2])}while(e==0)}a=e;b=b[c]=a>=0}return b};!K||U("9");!L&&!K||K&&U("9")||L&&U("1.9.1");K&&U("9");x("","pagead2.googlesyndication.com");var ha=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(g,a[c],c,a)},V=function(a){return!!a&&(a.indexOf("?google_debug")>0||a.indexOf("&google_debug")>0)};var W=function(){this.c=[];this.a={};for(var a=0,b=arguments.length;a<b;++a)this.a[arguments[a]]=""};W.prototype.h=function(a){if(this.a.hasOwnProperty(a))return this.a[a];return""};W.prototype.geil=W.prototype.h;var ia=function(a){var b=[],c=function(d){d!=""&&b.push(d)};ha(a.a,c);if(a.c.length>0&&b.length>0)return a.c.join(",")+","+b.join(",");return a.c.join(",")+b.join(",")};function ja(a){var b="adsense";if(a&&typeof a=="string"&&a.length>0)if(b==g)a=g;else{var c=window.GS_googleServiceIds_[b];if(c==g){c=b=="adsense"?new X:new Y;window.GS_googleServiceIds_[b]=c}b:{for(b=0;b<c.b.length;b++)if(a==c.b[b])break b;c.b[c.b.length]=a}a=c}else a=g;return a}r("GS_googleAddAdSenseService",ja);function ka(){for(var a in window.GS_googleServiceIds_){var b=window.GS_googleServiceIds_[a];typeof b!="function"&&b.enable()}}r("GS_googleEnableAllServices",ka);
function la(){window.GS_googleServiceIds_={}}r("GS_googleResetAllServices",la);function ma(){var a="adsense";a=a==g?g:window.GS_googleServiceIds_[a];return a=a==g?"":a.b.join()}r("GS_googleGetIdsForAdSenseService",ma);function na(a){return Z(a)}r("GS_googleFindService",na);function oa(){var a=Z("adsense");return a?ia(a.e):""}r("GS_googleGetExpIdsForAdSense",oa);function $(a){this.j=a;this.b=[];this.e=new W}
$.prototype.toString=function(){for(var a="["+this.j+" ids: ",b=0;b<this.b.length;b++){if(b>0)a+=",";a+=this.b[b]}a+="]";return a};var Z=function(a){return a=a==g?g:window.GS_googleServiceIds_[a]};function Y(){$.call(this,"unknown")}t(Y,$);Y.prototype.enable=function(){};function X(){$.call(this,"adsense");this.f=k}t(X,$);
var pa=function(a,b){var c;c=a;var d=Z("adsense"),e;var f=d.e;d=["32942002"];var h;h=e?f.a.hasOwnProperty(e)&&f.a[e]=="":true;if(h&&!(Math.random()<1.0E-4)&&Math.random()<b){h=Math.floor(Math.random()*d.length);d=d[h];if(d=="")e="";else if(e)if(f.a.hasOwnProperty(e))e=f.a[e]=d;else e="";else{f.c.push(d);e=d}}else e="";c=e==="32942002"||c&&(c.indexOf("?use_google_ads2")>0||c.indexOf("&use_google_ads2")>0)?true:k;if(c){if(V(a))return"google_ads_dbg2.js";return"google_ads2.js"}else{if(V(a))return"google_ads_dbg.js";
return"google_ads.js"}};
X.prototype.enable=function(){if(!this.f){var a;a=pa(document.URL,aa);var b="http://"+x("","partner.googleadservices.com");if(ba)b="https://"+x("","securepubads.g.doubleclick.net");var c="",d;d=C();(d=d=="pubads.g.doubleclick.net")||(c="?prodhost="+C());a=b+"/gampad/"+a+c;b="script";document.write("<"+b+' src="'+a+'"><\/script>');this.f=true;if(window.GA_jstiming&&window.GA_jstiming.Timer){window.GA_jstiming.load.name="load";window.GA_jstiming.load.tick("start")}}};
window.GS_googleServiceIds_||(window.GS_googleServiceIds_={});})()
