package org.openxdata.modules.workflows.model.shared;
// Generated Aug 8, 2010 5:31:25 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import org.openxdata.server.admin.model.AbstractEditable;

/**
 * DBSpecification generated by hbm2java
 */
public class DBSpecification extends AbstractEditable implements
        java.io.Serializable
{
    private Integer id = 0;
    private String specId;
    private String version;
    private String name;
    private String xml;
    private Set specStudyMapses = new HashSet(0);

    public DBSpecification()
    {
    }

    public DBSpecification(String specName, String version, String xml)
    {
        this.name = specName;
        this.specId = specName + version;
        this.version = version;
        this.xml = xml;
    }

    public DBSpecification(String specId, String xml, Set specStudyMapses)
    {
        this.specId = specId;
        this.xml = xml;
        this.specStudyMapses = specStudyMapses;
    }

    @Override
    public int getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getSpecId()
    {
        return this.specId;
    }

    public void setSpecId(String specId)
    {
        this.specId = specId;
    }

    public String getXml()
    {
        return this.xml;
    }

    public void setXml(String xml)
    {
        this.xml = xml;
    }

    public Set getSpecStudyMapses()
    {
        return this.specStudyMapses;
    }

    public void setSpecStudyMapses(Set specStudyMapses)
    {
        this.specStudyMapses = specStudyMapses;
    }

    public String getVersion()
    {
        return version;
    }

    public void setVersion(String version)
    {
        this.version = version;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }


}
